
USE Finleap;

CREATE  TABLE IF NOT EXISTS Finleap.FLCITY (
  CITYID      INT         AUTO_INCREMENT,
  CITYNAME    VARCHAR(64) NOT NULL,
  CITYLONG    VARCHAR(100) NOT NULL ,
  CITYLATI    VARCHAR(100) ,
  CITYSTATUS  INT  DEFAULT 0,
  CITYTIMEST   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UC_FLCITY  UNIQUE (CITYID,CITYNAME) ,
  PRIMARY KEY (CITYID,CITYNAME)
);

commit;

CREATE  TABLE IF NOT EXISTS Finleap.FLTEMP (
  TEMPID      INT         AUTO_INCREMENT,
  TEMPCITYID  INT         NOT NULL,
  TEMPMIN     FLOAT       DEFAULT 0.00  NOT NULL ,
  TEMPMAX     FLOAT       DEFAULT 0.00  NOT NULL ,
  TEMPTIMEST   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UC_FLTEMP  UNIQUE (TEMPID) ,
  PRIMARY KEY (TEMPID)
);

commit;

CREATE  TABLE IF NOT EXISTS Finleap.FLWEBH (
  WEBHID      INT         AUTO_INCREMENT,
  WEBHCITYID  INT         NOT NULL,
  WEBHURL     VARCHAR(250) NOT NULL,
  WEBHSTATUS  INT          DEFAULT 0 NOT NULL,
  WEBHTIMEST   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UC_FLWEBH  UNIQUE (WEBHID) ,
  PRIMARY KEY (WEBHID)
);

commit;

